import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {buildPlanningRepairInstructions} from '../services/aiCampaignCopilot/planningRepairInstructions.js';
import {electionMilestoneViolations,timelineCompletenessViolations,withCycleEvidenceAssessment} from '../services/aiCampaignCopilot/planningIntegrity.js';
const scope={strict_temporal:true,cycle_year:2030,election_window_start:'2026-10-01',election_window_end:'2030-12-31'};
const prompt='Create a full campaign timeline';
const valid='### GOTV Execution\n- Timing: October 2030 to November 2030\n### Election Day Operations\n- Timing: November 2030 (provisional; verify)';
const source=fs.readFileSync(new URL('../services/aiCampaignCopilot.service.js',import.meta.url),'utf8');
test('repair instructions carry specific deduplicated violations, selected year and explicit structure',()=>{
 const text=buildPlanningRepairInstructions({prompt,temporalScope:scope,violations:['Wrong GOTV year','Wrong GOTV year','Missing election day']});assert.equal((text.match(/Wrong GOTV year/g)||[]).length,1);assert.ok(text.includes('2030'));assert.ok(text.includes('GOTV Execution'));assert.ok(text.includes('Timing field'));assert.ok(text.includes('Missing election day'));
});
test('ordinary preparation repair does not force full election coverage',()=>assert.ok(!buildPlanningRepairInstructions({prompt:'Prepare a training plan',temporalScope:scope}).includes('This is a FULL timeline')));
test('actual repair request includes detected issues and preserves single-call behavior',async()=>{
 const fn=source.match(/async function repairTemporalAnswer\([\s\S]*?\n\}/)[0];let request,calls=0;
 const ctx={buildPlanningRepairInstructions,OPENAI_MODEL:'mock',clean:x=>String(x).trim(),openai:{chat:{completions:{create:async arg=>{request=arg;calls++;return {choices:[{message:{content:valid}}]};}}}}};vm.createContext(Object.assign(ctx, { process: { env: {} } }));vm.runInContext(fn+';this.repair=repairTemporalAnswer;',ctx);
 const reply=await ctx.repair({answer:'bad draft',prompt,temporalScope:scope,violations:['GOTV execution uses 2029']});assert.equal(calls,1);assert.equal(reply,valid);assert.ok(request.messages[1].content.includes('GOTV execution uses 2029'));assert.ok(request.messages[1].content.includes('bad draft'));
});
function pipeline(repair){let received;const ctx={generated:{answer:'Preparation only'},platformContext:{scope:{cycle_evidence:{matched_records:0}}},prompt,temporalScope:scope,isPlanningRequest:()=>true,temporalViolations:electionMilestoneViolations,timelineCompletenessViolations,withCycleEvidenceAssessment,repairTemporalAnswer:async args=>{received=args;return repair;}};vm.createContext(Object.assign(ctx, { process: { env: {} } }));const start=source.indexOf('  answer = generated.answer;'),end=source.indexOf('  confidence = generated.confidence ??',start);return {run:()=>vm.runInContext('(async()=>{let answer;'+source.slice(start,end)+';return answer;})()',ctx),received:()=>received};}
test('response pipeline supplies failed checks to repair and accepts a validated result once',async()=>{const p=pipeline(valid);const answer=await p.run();assert.ok(p.received().violations.length===2);assert.equal((answer.match(/Cycle evidence assessment/gi)||[]).length,1);});
test('failed repair remains rejected with structured violations and cycle',async()=>{const p=pipeline('Still preparation only');await assert.rejects(p.run(),error=>error.statusCode===422&&error.code==='TEMPORAL_SCOPE_VIOLATION'&&error.violations.length===2&&error.cycle===2030);});
function routeHarness(outcome){let callback,middleware;const code=fs.readFileSync(new URL('../routes/aiCampaignCopilot.routes.js',import.meta.url),'utf8').replace(/^import[\s\S]*?const router = express.Router\(\);/,'const router = express.Router();').replace(/export default router\s*;?/,'');const auth=()=>{};const ctx={express:{Router:()=>({get:()=>{},post:(p,m,cb)=>{middleware=m;callback=cb;}})},requireAuth:auth,askAiCampaignCopilot:async()=>{if(outcome instanceof Error)throw outcome;return outcome;},console:{error:()=>{}}};vm.createContext(Object.assign(ctx, { process: { env: {} } }));vm.runInContext(code,ctx);assert.equal(middleware,auth);let status=200,body;return {run:async()=>{await callback({user:{id:1},body:{}},{status:n=>{status=n;return {json:v=>{body=v;}};},json:v=>{body=v;}});return {status,body};}};}
test('actual ask route returns 422 with feedback fields and keeps authentication',async()=>{const e=Object.assign(new Error('Invalid calendar'),{code:'TEMPORAL_SCOPE_VIOLATION',violations:['Bad date'],cycle:2030});const r=await routeHarness(e).run();assert.equal(r.status,422);assert.equal(r.body.code,e.code);assert.equal(r.body.violations[0],'Bad date');assert.equal(r.body.cycle,2030);});
test('unexpected route failures remain 500 and successful answers remain 200',async()=>{assert.equal((await routeHarness(new Error('Unexpected')).run()).status,500);const good=await routeHarness({answer:valid}).run();assert.equal(good.status,200);assert.equal(good.body.answer,valid);});
